<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLaIO58D\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLaIO58D/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLaIO58D.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLaIO58D\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLaIO58D\App_KernelDevDebugContainer([
    'container.build_hash' => 'LaIO58D',
    'container.build_id' => 'ef65325e',
    'container.build_time' => 1625415159,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLaIO58D');
